on:
  push:
    branches:
      - main

    paths: &paths
      - '.github/workflows/cache-packages.yaml'

      - 'src/**/*.c'
      - 'src/**/*.h'
      - 'CMakeLists.txt'

      - '**/*.nix'
      - '!devenv.nix'
      - 'flake.lock'

  pull_request:
    paths: *paths

  workflow_dispatch:

concurrency:
  # one run per branch; latest completes last
  group: ${{ github.workflow }}-${{ github.ref }}

  cancel-in-progress: false

jobs:
  collect-targets:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.collect-packages.outputs.packages }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1
        with:
          extra_nix_config: &extra_nix_config |
            accept-flake-config = true

      - id: collect-packages
        run: |
          echo "packages=$(jq -cn \
            --argjson systems "$(nix eval .#packages --apply builtins.attrNames --json)" \
            '{
              include: ($systems | map({target: "packages.\(.).default"}))
            }')" >> $GITHUB_OUTPUT

  build-packages:
    needs: collect-targets

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.collect-targets.outputs.packages) }}

      fail-fast: false

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1
        with:
          extra_nix_config: *extra_nix_config

      - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
        with:
          primary-key: packages-${{ matrix.target }}-${{ hashFiles('**/*.nix', '!devenv.nix', 'flake.lock') }}

          restore-prefixes-first-match: |
            packages-${{ matrix.target }}-
            packages-

      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: hilorioze

          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

          skipPush: ${{ github.event_name == 'pull_request' }}

      - run: nix build .#${{ matrix.target }} -L
